// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebkushndswpahuqvsysj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVia3VzaG5kc3dwYWh1cXZzeXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODc5NTEsImV4cCI6MjA2NDc2Mzk1MX0.50fKmKlAsPXchhQgqE07MThCtladbKc71u-koTUnQSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);